# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audio_tagger.ui',
# licensing of 'audio_tagger.ui' applies.
#
# Created: Thu Dec 19 13:10:34 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter = QtWidgets.QSplitter(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.file_frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_frame.sizePolicy().hasHeightForWidth())
        self.file_frame.setSizePolicy(sizePolicy)
        self.file_frame.setObjectName("file_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.file_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pb_prev = QtWidgets.QPushButton(self.file_frame)
        self.pb_prev.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/left"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_prev.setIcon(icon)
        self.pb_prev.setIconSize(QtCore.QSize(10, 10))
        self.pb_prev.setFlat(True)
        self.pb_prev.setObjectName("pb_prev")
        self.horizontalLayout_5.addWidget(self.pb_prev)
        self.pb_next = QtWidgets.QPushButton(self.file_frame)
        self.pb_next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/right"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_next.setIcon(icon1)
        self.pb_next.setIconSize(QtCore.QSize(10, 10))
        self.pb_next.setFlat(True)
        self.pb_next.setObjectName("pb_next")
        self.horizontalLayout_5.addWidget(self.pb_next)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.file_tree = QtWidgets.QTreeWidget(self.file_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_tree.sizePolicy().hasHeightForWidth())
        self.file_tree.setSizePolicy(sizePolicy)
        self.file_tree.setMinimumSize(QtCore.QSize(250, 0))
        self.file_tree.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.file_tree.setUniformRowHeights(True)
        self.file_tree.setObjectName("file_tree")
        self.file_tree.headerItem().setText(0, "1")
        self.file_tree.header().setVisible(True)
        self.verticalLayout_5.addWidget(self.file_tree)
        self.spectro_frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectro_frame.sizePolicy().hasHeightForWidth())
        self.spectro_frame.setSizePolicy(sizePolicy)
        self.spectro_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spectro_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spectro_frame.setObjectName("spectro_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.spectro_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gw_overview = QtWidgets.QGraphicsView(self.spectro_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gw_overview.sizePolicy().hasHeightForWidth())
        self.gw_overview.setSizePolicy(sizePolicy)
        self.gw_overview.setObjectName("gw_overview")
        self.horizontalLayout_2.addWidget(self.gw_overview)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollView = QtWidgets.QGraphicsView(self.spectro_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollView.sizePolicy().hasHeightForWidth())
        self.scrollView.setSizePolicy(sizePolicy)
        self.scrollView.setObjectName("scrollView")
        self.horizontalLayout_3.addWidget(self.scrollView)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.frame1 = QtWidgets.QFrame(self.spectro_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1.sizePolicy().hasHeightForWidth())
        self.frame1.setSizePolicy(sizePolicy)
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.frame1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.frame1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.frame1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.verticalLayout_7.addWidget(self.frame1)
        self.horizontalLayout_7.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_spec_create = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_spec_create.setObjectName("lbl_spec_create")
        self.horizontalLayout_13.addWidget(self.lbl_spec_create)
        self.pb_toggle_create = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_toggle_create.sizePolicy().hasHeightForWidth())
        self.pb_toggle_create.setSizePolicy(sizePolicy)
        self.pb_toggle_create.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/toggle-off"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/toggle-off"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/toggle-on"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.pb_toggle_create.setIcon(icon2)
        self.pb_toggle_create.setIconSize(QtCore.QSize(20, 20))
        self.pb_toggle_create.setCheckable(True)
        self.pb_toggle_create.setFlat(True)
        self.pb_toggle_create.setObjectName("pb_toggle_create")
        self.horizontalLayout_13.addWidget(self.pb_toggle_create)
        self.lbl_spec_modify = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_spec_modify.setObjectName("lbl_spec_modify")
        self.horizontalLayout_13.addWidget(self.lbl_spec_modify)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.pb_first_tag = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_first_tag.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/first"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_first_tag.setIcon(icon3)
        self.pb_first_tag.setIconSize(QtCore.QSize(20, 20))
        self.pb_first_tag.setFlat(True)
        self.pb_first_tag.setObjectName("pb_first_tag")
        self.horizontalLayout_13.addWidget(self.pb_first_tag)
        self.pb_previous_tag = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_previous_tag.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/backward"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_previous_tag.setIcon(icon4)
        self.pb_previous_tag.setIconSize(QtCore.QSize(20, 20))
        self.pb_previous_tag.setFlat(True)
        self.pb_previous_tag.setObjectName("pb_previous_tag")
        self.horizontalLayout_13.addWidget(self.pb_previous_tag)
        self.pb_next_tag = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_next_tag.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/forward"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_next_tag.setIcon(icon5)
        self.pb_next_tag.setIconSize(QtCore.QSize(20, 20))
        self.pb_next_tag.setFlat(True)
        self.pb_next_tag.setObjectName("pb_next_tag")
        self.horizontalLayout_13.addWidget(self.pb_next_tag)
        self.pb_last_tag = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_last_tag.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/last"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_last_tag.setIcon(icon6)
        self.pb_last_tag.setIconSize(QtCore.QSize(20, 20))
        self.pb_last_tag.setFlat(True)
        self.pb_last_tag.setObjectName("pb_last_tag")
        self.horizontalLayout_13.addWidget(self.pb_last_tag)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.pb_save = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_save.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_save.setIcon(icon7)
        self.pb_save.setIconSize(QtCore.QSize(20, 20))
        self.pb_save.setFlat(True)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_13.addWidget(self.pb_save)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.cb_labelType = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_labelType.setObjectName("cb_labelType")
        self.horizontalLayout_16.addWidget(self.cb_labelType)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.btn_done = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_done.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/toggle-off"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/toggle-on"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btn_done.setIcon(icon8)
        self.btn_done.setIconSize(QtCore.QSize(20, 20))
        self.btn_done.setCheckable(True)
        self.btn_done.setFlat(True)
        self.btn_done.setObjectName("btn_done")
        self.horizontalLayout_4.addWidget(self.btn_done)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.info_viewer = QtWidgets.QTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_viewer.sizePolicy().hasHeightForWidth())
        self.info_viewer.setSizePolicy(sizePolicy)
        self.info_viewer.setMaximumSize(QtCore.QSize(16777215, 150))
        self.info_viewer.setObjectName("info_viewer")
        self.gridLayout.addWidget(self.info_viewer, 0, 2, 1, 1)
        self.sound_controller = SoundController(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sound_controller.sizePolicy().hasHeightForWidth())
        self.sound_controller.setSizePolicy(sizePolicy)
        self.sound_controller.setObjectName("sound_controller")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sound_controller)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addWidget(self.sound_controller, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.actionClass_settings = QtWidgets.QAction(MainWindow)
        self.actionClass_settings.setObjectName("actionClass_settings")
        self.actionExport_settings = QtWidgets.QAction(MainWindow)
        self.actionExport_settings.setObjectName("actionExport_settings")
        self.actionImport_settings = QtWidgets.QAction(MainWindow)
        self.actionImport_settings.setObjectName("actionImport_settings")
        self.menuFile.addAction(self.actionOpen_folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClass_settings)
        self.menuFile.addAction(self.actionExport_settings)
        self.menuFile.addAction(self.actionImport_settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionOpen_folder)
        self.toolBar.addAction(self.actionClass_settings)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pb_prev.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Show previous audio file", None, -1))
        self.pb_next.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Show next audio file", None, -1))
        self.file_tree.setSortingEnabled(True)
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Position", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Vertical zoom:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Annotations", None, -1))
        self.lbl_spec_create.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None, -1))
        self.lbl_spec_modify.setText(QtWidgets.QApplication.translate("MainWindow", "Modify", None, -1))
        self.pb_first_tag.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Go to first annotation", None, -1))
        self.pb_previous_tag.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Previous annotation", None, -1))
        self.pb_next_tag.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Next annotation", None, -1))
        self.pb_last_tag.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Go to last annotation", None, -1))
        self.pb_save.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Active label:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "File Done:", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.actionOpen_folder.setText(QtWidgets.QApplication.translate("MainWindow", "Open folder", None, -1))
        self.actionClass_settings.setText(QtWidgets.QApplication.translate("MainWindow", "Class settings", None, -1))
        self.actionExport_settings.setText(QtWidgets.QApplication.translate("MainWindow", "Export settings", None, -1))
        self.actionImport_settings.setText(QtWidgets.QApplication.translate("MainWindow", "Import settings", None, -1))

from AudioTagger.sound_controller import SoundController
import resources_rc
