# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_mod.ui',
# licensing of 'gui_mod.ui' applies.
#
# Created: Fri May 31 16:02:22 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cb_file = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_file.sizePolicy().hasHeightForWidth())
        self.cb_file.setSizePolicy(sizePolicy)
        self.cb_file.setObjectName("cb_file")
        self.horizontalLayout_5.addWidget(self.cb_file)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pb_prev = QtWidgets.QPushButton(self.centralwidget)
        self.pb_prev.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/left"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_prev.setIcon(icon)
        self.pb_prev.setFlat(True)
        self.pb_prev.setObjectName("pb_prev")
        self.horizontalLayout_5.addWidget(self.pb_prev)
        self.pb_next = QtWidgets.QPushButton(self.centralwidget)
        self.pb_next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/right"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_next.setIcon(icon1)
        self.pb_next.setFlat(True)
        self.pb_next.setObjectName("pb_next")
        self.horizontalLayout_5.addWidget(self.pb_next)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gw_overview = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gw_overview.sizePolicy().hasHeightForWidth())
        self.gw_overview.setSizePolicy(sizePolicy)
        self.gw_overview.setObjectName("gw_overview")
        self.horizontalLayout_2.addWidget(self.gw_overview)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollView.sizePolicy().hasHeightForWidth())
        self.scrollView.setSizePolicy(sizePolicy)
        self.scrollView.setObjectName("scrollView")
        self.horizontalLayout_3.addWidget(self.scrollView)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSpacing(9)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.info_viewer = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_viewer.sizePolicy().hasHeightForWidth())
        self.info_viewer.setSizePolicy(sizePolicy)
        self.info_viewer.setMaximumSize(QtCore.QSize(16777215, 80))
        self.info_viewer.setObjectName("info_viewer")
        self.gridLayout.addWidget(self.info_viewer, 4, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pb_stop = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_stop.sizePolicy().hasHeightForWidth())
        self.pb_stop.setSizePolicy(sizePolicy)
        self.pb_stop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/stop"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_stop.setIcon(icon2)
        self.pb_stop.setIconSize(QtCore.QSize(20, 20))
        self.pb_stop.setFlat(True)
        self.pb_stop.setObjectName("pb_stop")
        self.horizontalLayout_11.addWidget(self.pb_stop)
        self.pb_play = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_play.sizePolicy().hasHeightForWidth())
        self.pb_play.setSizePolicy(sizePolicy)
        self.pb_play.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/play"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/play"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/pause"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.pb_play.setIcon(icon3)
        self.pb_play.setIconSize(QtCore.QSize(20, 20))
        self.pb_play.setCheckable(True)
        self.pb_play.setFlat(True)
        self.pb_play.setObjectName("pb_play")
        self.horizontalLayout_11.addWidget(self.pb_play)
        self.pb_seek = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_seek.sizePolicy().hasHeightForWidth())
        self.pb_seek.setSizePolicy(sizePolicy)
        self.pb_seek.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/signs"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_seek.setIcon(icon4)
        self.pb_seek.setIconSize(QtCore.QSize(20, 20))
        self.pb_seek.setFlat(True)
        self.pb_seek.setObjectName("pb_seek")
        self.horizontalLayout_11.addWidget(self.pb_seek)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.cb_followSound = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_followSound.sizePolicy().hasHeightForWidth())
        self.cb_followSound.setSizePolicy(sizePolicy)
        self.cb_followSound.setObjectName("cb_followSound")
        self.horizontalLayout_15.addWidget(self.cb_followSound)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        self.cb_playbackSpeed = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_playbackSpeed.sizePolicy().hasHeightForWidth())
        self.cb_playbackSpeed.setSizePolicy(sizePolicy)
        self.cb_playbackSpeed.setObjectName("cb_playbackSpeed")
        self.horizontalLayout_15.addWidget(self.cb_playbackSpeed)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.cb_specType = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_specType.sizePolicy().hasHeightForWidth())
        self.cb_specType.setSizePolicy(sizePolicy)
        self.cb_specType.setObjectName("cb_specType")
        self.cb_specType.addItem("")
        self.cb_specType.addItem("")
        self.horizontalLayout_4.addWidget(self.cb_specType)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_spec_create = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_spec_create.setObjectName("lbl_spec_create")
        self.horizontalLayout_13.addWidget(self.lbl_spec_create)
        self.pb_toggle_create = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_toggle_create.sizePolicy().hasHeightForWidth())
        self.pb_toggle_create.setSizePolicy(sizePolicy)
        self.pb_toggle_create.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/toggle-off"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/toggle-off"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/toggle-on"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.pb_toggle_create.setIcon(icon5)
        self.pb_toggle_create.setIconSize(QtCore.QSize(20, 20))
        self.pb_toggle_create.setCheckable(True)
        self.pb_toggle_create.setFlat(True)
        self.pb_toggle_create.setObjectName("pb_toggle_create")
        self.horizontalLayout_13.addWidget(self.pb_toggle_create)
        self.lbl_spec_modify = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_spec_modify.setObjectName("lbl_spec_modify")
        self.horizontalLayout_13.addWidget(self.lbl_spec_modify)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.pb_toggle_back = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_toggle_back.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/backward"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_toggle_back.setIcon(icon6)
        self.pb_toggle_back.setIconSize(QtCore.QSize(20, 20))
        self.pb_toggle_back.setFlat(True)
        self.pb_toggle_back.setObjectName("pb_toggle_back")
        self.horizontalLayout_13.addWidget(self.pb_toggle_back)
        self.pb_toggle = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_toggle.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/forward"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_toggle.setIcon(icon7)
        self.pb_toggle.setIconSize(QtCore.QSize(20, 20))
        self.pb_toggle.setFlat(True)
        self.pb_toggle.setObjectName("pb_toggle")
        self.horizontalLayout_13.addWidget(self.pb_toggle)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.pb_save = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_save.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_save.setIcon(icon8)
        self.pb_save.setIconSize(QtCore.QSize(20, 20))
        self.pb_save.setFlat(True)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_13.addWidget(self.pb_save)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.cb_labelType = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_labelType.setObjectName("cb_labelType")
        self.horizontalLayout_16.addWidget(self.cb_labelType)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.gridLayout.addLayout(self.horizontalLayout_12, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.actionClass_settings = QtWidgets.QAction(MainWindow)
        self.actionClass_settings.setObjectName("actionClass_settings")
        self.actionExport_settings = QtWidgets.QAction(MainWindow)
        self.actionExport_settings.setObjectName("actionExport_settings")
        self.actionImport_settings = QtWidgets.QAction(MainWindow)
        self.actionImport_settings.setObjectName("actionImport_settings")
        self.menuFile.addAction(self.actionOpen_folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClass_settings)
        self.menuFile.addAction(self.actionExport_settings)
        self.menuFile.addAction(self.actionImport_settings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pb_prev.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Show previous audio file", None, -1))
        self.pb_next.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Show next audio file", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Sound controls", None, -1))
        self.pb_stop.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.pb_play.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Play", None, -1))
        self.pb_seek.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Seek", None, -1))
        self.cb_followSound.setText(QtWidgets.QApplication.translate("MainWindow", "follow sound", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "playback speed:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "spectrogram type:", None, -1))
        self.cb_specType.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "audible range", None, -1))
        self.cb_specType.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "ultra sonic range", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Annotations", None, -1))
        self.lbl_spec_create.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None, -1))
        self.lbl_spec_modify.setText(QtWidgets.QApplication.translate("MainWindow", "Modify", None, -1))
        self.pb_toggle_back.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Previous annotation", None, -1))
        self.pb_toggle.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Next annotation", None, -1))
        self.pb_save.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Active label:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Position", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Vertical zoom:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionOpen_folder.setText(QtWidgets.QApplication.translate("MainWindow", "Open folder", None, -1))
        self.actionClass_settings.setText(QtWidgets.QApplication.translate("MainWindow", "Class settings", None, -1))
        self.actionExport_settings.setText(QtWidgets.QApplication.translate("MainWindow", "Export settings", None, -1))
        self.actionImport_settings.setText(QtWidgets.QApplication.translate("MainWindow", "Import settings", None, -1))

import resources_rc
