# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tag_dialog.ui',
# licensing of 'tag_dialog.ui' applies.
#
# Created: Fri Aug 23 16:06:10 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_TagDialog(object):
    def setupUi(self, TagDialog):
        TagDialog.setObjectName("TagDialog")
        TagDialog.resize(973, 652)
        self.verticalLayout = QtWidgets.QVBoxLayout(TagDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(TagDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setStyleSheet("font-weight:bold")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon)
        self.btn_add.setIconSize(QtCore.QSize(16, 16))
        self.btn_add.setFlat(True)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_8.addWidget(self.btn_add)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.tag_list = QtWidgets.QListView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tag_list.sizePolicy().hasHeightForWidth())
        self.tag_list.setSizePolicy(sizePolicy)
        self.tag_list.setObjectName("tag_list")
        self.verticalLayout_2.addWidget(self.tag_list)
        self.tag_form = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tag_form.sizePolicy().hasHeightForWidth())
        self.tag_form.setSizePolicy(sizePolicy)
        self.tag_form.setObjectName("tag_form")
        self.gridLayout = QtWidgets.QGridLayout(self.tag_form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.tag_form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tag_form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tag_form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_color = QtWidgets.QPushButton(self.tag_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_color.sizePolicy().hasHeightForWidth())
        self.btn_color.setSizePolicy(sizePolicy)
        self.btn_color.setAutoFillBackground(True)
        self.btn_color.setText("")
        self.btn_color.setObjectName("btn_color")
        self.horizontalLayout_2.addWidget(self.btn_color)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.lbl_related_tags = QtWidgets.QLabel(self.tag_form)
        self.lbl_related_tags.setText("")
        self.lbl_related_tags.setObjectName("lbl_related_tags")
        self.gridLayout.addWidget(self.lbl_related_tags, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tag_form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.input_name = QtWidgets.QLineEdit(self.tag_form)
        self.input_name.setObjectName("input_name")
        self.horizontalLayout_5.addWidget(self.input_name)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(self.tag_form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_keyseq = KeySequenceEdit(self.tag_form)
        self.input_keyseq.setObjectName("input_keyseq")
        self.horizontalLayout_4.addWidget(self.input_keyseq)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 5, 0, 1, 2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.btn_delete = QtWidgets.QPushButton(self.tag_form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btn_delete.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/delete"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon1)
        self.btn_delete.setFlat(True)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_9.addWidget(self.btn_delete)
        self.gridLayout.addLayout(self.horizontalLayout_9, 6, 0, 1, 2)
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(TagDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TagDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), TagDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), TagDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TagDialog)

    def retranslateUi(self, TagDialog):
        TagDialog.setWindowTitle(QtWidgets.QApplication.translate("TagDialog", "Dialog", None, -1))
        self.btn_add.setText(QtWidgets.QApplication.translate("TagDialog", "  Add new tag", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("TagDialog", "Key shortcut:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("TagDialog", "Related tags:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("TagDialog", "Tag Name:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("TagDialog", "Border Color:", None, -1))
        self.input_name.setPlaceholderText(QtWidgets.QApplication.translate("TagDialog", "Tag name", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("TagDialog", "Manage related tags", None, -1))
        self.input_keyseq.setPlaceholderText(QtWidgets.QApplication.translate("TagDialog", "Key shortcut", None, -1))
        self.btn_delete.setText(QtWidgets.QApplication.translate("TagDialog", "Delete Tag", None, -1))

from AudioTagger.keysequenceedit import KeySequenceEdit
import resources_rc
